### ISSUE TITLE
one filter works but multiple filters fails to work with crossfilter

### ISSUE THREAD

**Issue by sherwaldeepesh** [lastlegion/dc.js-server-side-crossfilter#3]
This is created with the help of your repository and zZohnson repository. I am new to Javascript and whole crossfilter thing, When this is created only on client side it works perfectly (Leave the Line Chart)
currently I am facing the issue that only one filter selection is worked properly per graph but if i tried to select more than one that the data may be start to increasing or not working properly with the multiple selection. Please take a look on it
Thanks.

[sde.zip](https://github.com/lastlegion/dc.js-server-side-crossfilter/files/3558242/sde.zip)

**Comment by lastlegion** [comment]
Hi @sherwaldeepesh I won't be able to download the zip file. Would it be possible to share the code snippet on gist or git and point me to what the log error messages are?

**Comment by sherwaldeepesh** [comment]
Please take a look on it
https://github.com/sherwaldeepesh/Crossfilter-server-side

**Comment by sherwaldeepesh** [comment]
Hi @lastlegion could you please help me with how can i send parameters for filterfunction or if any alternative, as i tried to use array of array didn't work properly.
